### ISSUE TITLE
support for runtimes other than tokio

### ISSUE THREAD

**Issue by danieleades** [danieleades/chesterfield#3]

**Comment by danieleades** [comment]
this is blocked upstream since this crate depends on reqwest, which does not allow to choose a runtime other than tokio.

Reqwest depends in turn on Hyper, which is where the implicit dependence on Tokio lies. Hyper has an option to use other runtimes, but Reqwest does not expose this.

see https://github.com/seanmonstar/reqwest/issues/557

**Comment by dgramop** [comment]
Hi! I'm fairly new to rust, so forgive me if . Is there any specific reason for using non-tokio runtimes?

**Comment by danieleades** [comment]
@dgramop
> Is there any specific reason for using non-tokio runtimes?

Nope. The Tokio runtime is, by all accounts, excellent. You'd do well as an application author to use it.

But that's not really the point. And this isn't a Rust-specific problem, it's a software architecture problem. This crate is a *library*, and a library shouldn't be deciding your runtime dependencies for your application (it should be the other way round). Worse, the fact that Request is tied to Tokio is *implicit*. It's completely non-obvious that you *can't* use a runtime other than Tokio.

Tomorrow, or the next day, when a new future executor is released that *does* have a clear advantage over Tokio (memory use, performance, security, binary size, etc) you'd like to be able to freely switch. Since right now you can't, you have a dependency inversion problem.

**Comment by danieleades** [comment]
looks like `smol` can be used with Hyper (by creating a global tokio executor)-
https://github.com/stjepang/smol/blob/master/examples/other-runtimes.rs

**Comment by danieleades** [comment]
i'm going to close this. This crate is compatible with 2 runtimes now. Any further improvements will require upstream changes.
